"""
Traceability Scanner — builds a cross-reference graph
of BA artifacts and reports coverage gaps, orphans, and dangling references.

Config-driven: artifact types, patterns, and scan rules are defined in graph-ba.toml.

Usage:
    trace-ba --root /path/to/project
    trace-ba --root . --json-out reports/graph.json --dot-out reports/graph.dot -v
"""
from __future__ import annotations

import ast
import json
import re
import sys
from collections import defaultdict
from dataclasses import dataclass, field
from datetime import datetime
from pathlib import Path
from typing import Dict, List, Optional, Set, Tuple

import click
import networkx as nx

from graph_ba.config import ProjectConfig, load_config, normalize_id, classify_id


# ── Data model ────────────────────────────────────────────────────

@dataclass
class Artifact:
    id: str
    artifact_type: str  # type ID from config (e.g. "ST", "BR_REQ")
    source_file: Path
    line_number: int
    title: str = ""


@dataclass
class Reference:
    target_id: str
    source_file: Path
    line_number: int
    context: str = ""


@dataclass
class CodeReference:
    """A @trace reference found in a source code file."""
    code_file: Path
    line_number: int
    target_ids: List[str]  # normalized artifact IDs
    context: str = ""      # the raw comment line
    rel_path: str = ""     # relative path from project root


@dataclass
class MiniRegistryTrace:
    """A trace edge declared on a mini Resource or CustomMethod."""
    source_id: str
    source_type: str
    title: str
    source_file: Path
    line_number: int
    target_id: str
    relation_type: str
    context: str = ""
    rel_path: str = ""


@dataclass
class ReactUiElement:
    """A React JSX UI trace attribute selected for graph import."""
    source_id: str
    source_type: str
    source_file: Path
    line_number: int
    selector: str
    target_id: str
    target_type: str
    relation_type: str
    role: str = "component"
    context: str = ""
    rel_path: str = ""


@dataclass
class MiniAdminSourceTrace:
    """A data-source dependency declared by a mini-admin custom screen."""
    source_id: str
    source_type: str
    title: str
    source_file: Path
    line_number: int
    target_id: str
    target_type: str
    relation_type: str
    context: str = ""
    rel_path: str = ""


@dataclass
class MiniAdminComponentTrace:
    """A component-level trace recovered from mini-admin UI ids and trace metadata."""
    screen_id: str
    component_id: str
    component_selector: str
    source_file: Path
    line_number: int
    target_id: str
    target_type: str
    relation_type: str
    context: str = ""
    rel_path: str = ""


@dataclass
class MiniAdminComponentTraceEntry:
    """Runtime overlay payload generated by graph-ba for a mini-admin UI id."""
    screen_id: str
    component_id: str
    selector: str
    aliases: List[str]
    source_keys: List[str]
    ac_ids: List[str]
    raw_ids: List[str]
    test_ids: List[str]
    trace_gap: str = ""


# ── Phase 1: Definition scanning ─────────────────────────────────

def _read_lines(path: Path) -> List[str]:
    return path.read_text(encoding="utf-8").splitlines()


def _register(registry: Dict[str, Artifact], art: Artifact, config: ProjectConfig):
    nid = normalize_id(art.id, config)
    art.id = nid
    if nid not in registry:
        registry[nid] = art


def scan_definitions(root: Path, config: ProjectConfig) -> Dict[str, Artifact]:
    """Scan artifact definitions using rules from config."""
    registry: Dict[str, Artifact] = {}

    for rule in config.definitions:
        file_str = rule.file
        # Support glob patterns in file field
        if '*' in file_str or '?' in file_str:
            # Glob: scan matching files
            matched = sorted(root.glob(file_str))
            for f in matched:
                if rule.mode == "heading":
                    _scan_heading(registry, f, rule.pattern, rule.type_id, config)
                elif rule.mode == "table":
                    _scan_table_first_col(registry, f, rule.pattern, rule.type_id, config)
        else:
            filepath = root / file_str
            if rule.mode == "heading":
                _scan_heading(registry, filepath, rule.pattern, rule.type_id, config)
            elif rule.mode == "table":
                _scan_table_first_col(registry, filepath, rule.pattern, rule.type_id, config)

    return registry


def _scan_heading(registry, filepath, pattern, type_id, config):
    if not filepath.exists():
        return
    for i, line in enumerate(_read_lines(filepath), 1):
        m = pattern.match(line)
        if m:
            raw_id = m.group(1)
            if raw_id is None:
                continue
            title = m.group(2).strip() if m.lastindex >= 2 else ""
            _register(registry, Artifact(raw_id, type_id, filepath, i, title), config)


def _scan_table_first_col(registry, filepath, pattern, type_id, config):
    if not filepath.exists():
        return
    for i, line in enumerate(_read_lines(filepath), 1):
        m = pattern.match(line)
        if m:
            raw_id = m.group(1)
            if raw_id is None:
                continue
            cols = [c.strip() for c in line.split("|")]
            title = cols[2] if len(cols) > 2 else ""
            _register(registry, Artifact(raw_id, type_id, filepath, i, title), config)


# ── Phase 2: Reference extraction ────────────────────────────────

def expand_ranges(text: str, config: ProjectConfig) -> List[str]:
    """Expand ranges like BR.12.1–BR.12.6 into individual IDs."""
    results = []
    for m in config.range_pattern.finditer(text):
        prefix, start_s, end_s = m.group(1), m.group(2), m.group(3)
        for i in range(int(start_s), int(end_s) + 1):
            results.append(f"{prefix}{i}")
    return results


def scan_index_cross_refs(
    root: Path, config: ProjectConfig
) -> List[Tuple[str, str, Path, int]]:
    """Parse index tables where first column is the 'source' artifact and other
    columns contain 'target' artifact IDs."""
    results: List[Tuple[str, str, Path, int]] = []

    for rule in config.index_tables:
        filepath = root / rule.file
        _parse_index_table(results, filepath, rule.first_col_pattern, config)

    return results


def _parse_index_table(
    results: List[Tuple[str, str, Path, int]],
    filepath: Path,
    first_col_re: re.Pattern,
    config: ProjectConfig,
):
    if not filepath.exists():
        return
    lines = _read_lines(filepath)
    for line_num, line in enumerate(lines, 1):
        m = first_col_re.match(line)
        if not m:
            continue
        source_id = normalize_id(m.group(1), config)
        rest = line[m.end():]

        # Find all artifact IDs in the rest of the row
        for tid, tdef in config.types.items():
            for rm in tdef.ref_pattern.finditer(rest):
                target_id = normalize_id(rm.group(1), config)
                if target_id != source_id:
                    results.append((source_id, target_id, filepath, line_num))

        # Also expand ranges
        for eid in expand_ranges(rest, config):
            nid = normalize_id(eid, config)
            if nid != source_id:
                results.append((source_id, nid, filepath, line_num))


def scan_references(
    root: Path,
    registry: Dict[str, Artifact],
    config: ProjectConfig,
) -> List[Reference]:
    """Scan all .md files for cross-references to known artifact types."""
    scan_dirs = [root / d for d in config.scan_dirs]
    md_files: List[Path] = []
    for d in scan_dirs:
        if d.exists():
            md_files.extend(sorted(d.rglob("*.md")))

    # Build restriction sets for types with restrict_to
    restrict_files: Dict[str, Set[Path]] = {}
    for tid, tdef in config.types.items():
        if tdef.restrict_to:
            files: Set[Path] = set()
            for pattern in tdef.restrict_to:
                p = root / pattern
                if p.is_file():
                    files.add(p)
                elif p.is_dir():
                    files.update(p.rglob("*.md"))
                else:
                    # Treat as glob
                    files.update(root.glob(pattern))
            restrict_files[tid] = files

    all_refs: List[Reference] = []

    for filepath in md_files:
        lines = _read_lines(filepath)
        in_code_fence = False
        current_section = ""

        for line_num, line in enumerate(lines, 1):
            stripped = line.strip()

            if stripped.startswith("```"):
                in_code_fence = not in_code_fence
                continue
            if in_code_fence:
                continue

            if stripped.startswith("## "):
                current_section = stripped.lstrip("# ").strip()

            # Expand ranges
            expanded = expand_ranges(line, config)
            for eid in expanded:
                nid = normalize_id(eid, config)
                all_refs.append(Reference(nid, filepath, line_num, current_section))

            # Match all type patterns
            for tid, tdef in config.types.items():
                # Check restriction
                if tid in restrict_files and filepath not in restrict_files[tid]:
                    continue

                for m in tdef.ref_pattern.finditer(line):
                    raw_id = m.group(1)
                    nid = normalize_id(raw_id, config)
                    all_refs.append(Reference(nid, filepath, line_num, current_section))

    return all_refs


# ── Phase 2b: Code / test reference extraction ───────────────────

def _scan_source_references(
    root: Path,
    dirs: List[str],
    extensions: List[str],
    extract_raw_ids,
    config: ProjectConfig,
) -> List[CodeReference]:
    """Generic per-line scanner over source files.

    `extract_raw_ids(line) -> List[str]` returns raw artifact ID candidates
    for a line; they are normalized and kept only if classifiable.
    """
    files: List[Path] = []
    for dir_str in dirs:
        d = root / dir_str
        if not d.exists():
            continue
        for ext in extensions:
            files.extend(sorted(d.rglob(f"*.{ext}")))

    return _scan_file_references(root, files, extract_raw_ids, config)


def _scan_file_references(
    root: Path,
    files: List[Path],
    extract_raw_ids,
    config: ProjectConfig,
) -> List[CodeReference]:
    results: List[CodeReference] = []

    for filepath in files:
        try:
            lines = filepath.read_text(encoding="utf-8").splitlines()
        except (UnicodeDecodeError, OSError):
            continue

        try:
            rel_path = str(filepath.relative_to(root))
        except ValueError:
            rel_path = str(filepath)

        for line_num, line in enumerate(lines, 1):
            target_ids = []
            for raw_id in extract_raw_ids(line):
                raw_id = raw_id.strip(".,;:")
                if not raw_id:
                    continue
                nid = normalize_id(raw_id, config)
                if classify_id(nid, config) is not None:
                    target_ids.append(nid)

            if target_ids:
                results.append(CodeReference(
                    code_file=filepath,
                    line_number=line_num,
                    target_ids=target_ids,
                    context=line.strip(),
                    rel_path=rel_path,
                ))

    return results


def scan_code_references(
    root: Path,
    config: ProjectConfig,
) -> List[CodeReference]:
    """Scan source code files for @trace comments referencing BA artifacts."""
    if not config.code or not config.code.comment_pattern:
        return []

    comment_re = config.code.comment_pattern

    def extract(line: str) -> List[str]:
        m = comment_re.match(line)
        if not m:
            return []
        raw_ids_str = m.group(1).strip()
        return [s.strip() for s in re.split(r'[,\s]+', raw_ids_str) if s.strip()]

    return _scan_source_references(
        root, config.code.dirs, config.code.extensions, extract, config)


def scan_test_references(
    root: Path,
    config: ProjectConfig,
) -> List[CodeReference]:
    """Scan test files for artifact ID references (TEST: nodes).

    Unlike code scanning, no @trace marker is required: any artifact ID
    matching a configured type ref pattern counts as test evidence.

    Files come from `dirs` (recursive, filtered by `extensions`) plus
    `files` glob patterns — the latter for colocated tests (e.g.
    `src/**/*.test.ts`) where scanning the whole dir would count ordinary
    source mentions as evidence.
    """
    if not config.tests:
        return []

    type_patterns = [tdef.ref_pattern for tdef in config.types.values()]

    def extract(line: str) -> List[str]:
        ids: List[str] = []
        for pattern in type_patterns:
            for m in pattern.finditer(line):
                ids.append(m.group(1))
        return ids

    refs = _scan_source_references(
        root, config.tests.dirs, config.tests.extensions, extract, config)

    if config.tests.files:
        glob_files: List[Path] = []
        for pattern in config.tests.files:
            glob_files.extend(sorted(root.glob(pattern)))
        seen = {r.code_file for r in refs}
        glob_files = [f for f in glob_files if f not in seen]
        refs.extend(_scan_file_references(root, glob_files, extract, config))

    return refs


def scan_ui_references(
    root: Path,
    config: ProjectConfig,
) -> List[CodeReference]:
    """Scan UI trace sidecar files for artifact ID references (UI: nodes).

    Files come from root-relative glob patterns in [ui].files. Like test
    scanning, no marker is required: any artifact ID matching a configured
    type ref pattern counts as a UI-to-artifact link.
    """
    if not config.ui:
        return []

    files: List[Path] = []
    for pattern in config.ui.files:
        files.extend(sorted(root.glob(pattern)))

    type_patterns = [tdef.ref_pattern for tdef in config.types.values()]

    def extract(line: str) -> List[str]:
        ids: List[str] = []
        for pattern in type_patterns:
            for m in pattern.finditer(line):
                ids.append(m.group(1))
        return ids

    return _scan_file_references(root, files, extract, config)


def scan_mini_registry_traces(
    root: Path,
    config: ProjectConfig,
) -> List[MiniRegistryTrace]:
    """Scan mini Resource(...) and CustomMethod(...) trace declarations.

    This is intentionally static AST parsing. graph-ba must not import a mini
    application just to learn its trace contract.
    """
    if not config.mini_registry:
        return []

    files: List[Path] = []
    for dir_str in config.mini_registry.dirs:
        d = root / dir_str
        if not d.exists():
            continue
        for ext in config.mini_registry.extensions:
            files.extend(sorted(d.rglob(f"*.{ext}")))
    for pattern in config.mini_registry.files:
        files.extend(sorted(root.glob(pattern)))

    seen: Set[Path] = set()
    traces: List[MiniRegistryTrace] = []
    for filepath in files:
        if filepath in seen or not filepath.is_file():
            continue
        seen.add(filepath)
        try:
            tree = ast.parse(filepath.read_text(encoding="utf-8"))
        except (SyntaxError, UnicodeDecodeError, OSError):
            continue
        try:
            rel_path = str(filepath.relative_to(root))
        except ValueError:
            rel_path = str(filepath)

        for node in ast.walk(tree):
            if not isinstance(node, ast.Call):
                continue
            call_name = _ast_call_name(node.func)
            if call_name == "Resource":
                source_key = _ast_kw_string(node, "name")
                title = _ast_kw_string(node, "title") or source_key or ""
                source_type = config.mini_registry.resource_type
                source_id = f"{source_type}:{source_key}" if source_key else ""
            elif call_name == "CustomMethod":
                source_key = _ast_kw_string(node, "code")
                title = _ast_kw_string(node, "title") or source_key or ""
                source_type = config.mini_registry.custom_method_type
                source_id = f"{source_type}:{source_key}" if source_key else ""
            else:
                continue
            if not source_id:
                continue

            links = _extract_trace_links(_ast_kw_value(node, "trace"))
            if not links:
                traces.append(MiniRegistryTrace(
                    source_id=source_id,
                    source_type=source_type,
                    title=title,
                    source_file=filepath,
                    line_number=getattr(node, "lineno", 0),
                    target_id="",
                    relation_type="",
                    context="mini_registry",
                    rel_path=rel_path,
                ))
                continue

            for raw_target, raw_relation in links:
                target_id = normalize_id(raw_target, config)
                if classify_id(target_id, config) is None:
                    continue
                traces.append(MiniRegistryTrace(
                    source_id=source_id,
                    source_type=source_type,
                    title=title,
                    source_file=filepath,
                    line_number=getattr(node, "lineno", 0),
                    target_id=target_id,
                    relation_type=_relation_type(raw_relation),
                    context="mini_registry_trace",
                    rel_path=rel_path,
                ))
    return traces


def scan_mini_admin_source_traces(
    root: Path,
    config: ProjectConfig,
) -> List[MiniAdminSourceTrace]:
    """Scan mini-admin `sources.ts` metadata into screen data dependencies.

    The scanner is intentionally static and literal-only. It understands the
    local source metadata style:
    - `resource: SOME_RESOURCES.key`
    - `derivedFrom: [SOME_RESOURCES.key, "resource_name"]`
    - `meta: { customMethods: ["method.code"] }`
    """
    if not config.mini_admin_sources:
        return []

    files: List[Path] = []
    for dir_str in config.mini_admin_sources.dirs:
        d = root / dir_str
        if not d.exists():
            continue
        for ext in config.mini_admin_sources.extensions:
            files.extend(sorted(d.rglob(f"*.{ext}")))
    for pattern in config.mini_admin_sources.files:
        files.extend(sorted(root.glob(pattern)))

    seen: Set[Path] = set()
    traces: List[MiniAdminSourceTrace] = []
    for filepath in files:
        if filepath in seen or not filepath.is_file():
            continue
        seen.add(filepath)
        try:
            text = filepath.read_text(encoding="utf-8")
        except (UnicodeDecodeError, OSError):
            continue
        try:
            rel_path = str(filepath.relative_to(root))
        except ValueError:
            rel_path = str(filepath)

        screen_id = _mini_admin_screen_id(filepath, root, config)
        if not screen_id:
            continue
        screen_type = classify_id(screen_id, config) or "SCREEN_FAMILY"
        constants_text = _read_sibling_ts_constants(filepath) + "\n" + text
        resource_constants = _extract_ts_resource_constants(constants_text)
        resources = _extract_ts_resources(text, resource_constants)
        custom_methods = _extract_ts_custom_methods(text)
        source_map = _extract_mini_admin_source_map(text, resource_constants)
        frontend_computed_sources = [
            key for key, value in source_map.items() if value.get("frontend_computed")
        ]
        title = screen_id

        for resource in sorted(resources):
            traces.append(MiniAdminSourceTrace(
                source_id=screen_id,
                source_type=screen_type,
                title=title,
                source_file=filepath,
                line_number=_line_number_for(text, resource),
                target_id=f"{config.mini_admin_sources.resource_type}:{resource}",
                target_type=config.mini_admin_sources.resource_type,
                relation_type=config.mini_admin_sources.relation_type,
                context="mini_admin_sources",
                rel_path=rel_path,
            ))
        for method_code in sorted(custom_methods):
            traces.append(MiniAdminSourceTrace(
                source_id=screen_id,
                source_type=screen_type,
                title=title,
                source_file=filepath,
                line_number=_line_number_for(text, method_code),
                target_id=f"{config.mini_admin_sources.custom_method_type}:{method_code}",
                target_type=config.mini_admin_sources.custom_method_type,
                relation_type=config.mini_admin_sources.relation_type,
                context="mini_admin_sources",
                rel_path=rel_path,
            ))
        for source_key in sorted(frontend_computed_sources):
            target_id = _frontend_computed_id(screen_id, source_key, config)
            traces.append(MiniAdminSourceTrace(
                source_id=screen_id,
                source_type=screen_type,
                title=title,
                source_file=filepath,
                line_number=_line_number_for(text, source_key),
                target_id=target_id,
                target_type=config.mini_admin_sources.frontend_computed_type,
                relation_type=config.mini_admin_sources.relation_type,
                context="mini_admin_sources",
                rel_path=rel_path,
            ))
    return traces


def scan_mini_admin_component_traces(
    root: Path,
    config: ProjectConfig,
) -> List[MiniAdminComponentTrace]:
    """Scan mini-admin component trace sidecars into component-level graph edges.

    This ties UI ids to canonical/raw acceptance ids and to the data-source
    contracts declared in the sibling `sources.ts`.
    """
    entries = build_mini_admin_component_trace_entries(root, config)
    traces: List[MiniAdminComponentTrace] = []
    for entry in entries:
        source_file = root / entry["rel_path"]
        line_number = int(entry.get("line_number", 0) or 0)
        component_id = str(entry["component_id"])
        screen_id = str(entry["screen_id"])
        selector = str(entry["selector"])
        for target_id in entry.get("ac_ids", []):
            traces.append(MiniAdminComponentTrace(
                screen_id=screen_id,
                component_id=component_id,
                component_selector=selector,
                source_file=source_file,
                line_number=line_number,
                target_id=str(target_id),
                target_type=classify_id(str(target_id), config) or "AC",
                relation_type=(
                    config.mini_admin_sources.trace_relation_type
                    if config.mini_admin_sources else "TRACES_TO"
                ),
                context="mini_admin_component_trace:AC",
                rel_path=str(entry["rel_path"]),
            ))
        for target_id in entry.get("raw_ids", []):
            traces.append(MiniAdminComponentTrace(
                screen_id=screen_id,
                component_id=component_id,
                component_selector=selector,
                source_file=source_file,
                line_number=line_number,
                target_id=str(target_id),
                target_type=classify_id(str(target_id), config) or "RAC",
                relation_type=(
                    config.mini_admin_sources.trace_relation_type
                    if config.mini_admin_sources else "TRACES_TO"
                ),
                context="mini_admin_component_trace:RAC",
                rel_path=str(entry["rel_path"]),
            ))
        for target_id in entry.get("resource_ids", []):
            traces.append(MiniAdminComponentTrace(
                screen_id=screen_id,
                component_id=component_id,
                component_selector=selector,
                source_file=source_file,
                line_number=line_number,
                target_id=str(target_id),
                target_type=(
                    config.mini_admin_sources.resource_type
                    if config.mini_admin_sources else "CRUDL_RESOURCE"
                ),
                relation_type=(
                    config.mini_admin_sources.relation_type
                    if config.mini_admin_sources else "DEPENDS_ON"
                ),
                context="mini_admin_component_trace:CRUDL",
                rel_path=str(entry["rel_path"]),
            ))
        for target_id in entry.get("custom_method_ids", []):
            traces.append(MiniAdminComponentTrace(
                screen_id=screen_id,
                component_id=component_id,
                component_selector=selector,
                source_file=source_file,
                line_number=line_number,
                target_id=str(target_id),
                target_type=(
                    config.mini_admin_sources.custom_method_type
                    if config.mini_admin_sources else "CUSTOM_METHOD"
                ),
                relation_type=(
                    config.mini_admin_sources.relation_type
                    if config.mini_admin_sources else "DEPENDS_ON"
                ),
                context="mini_admin_component_trace:CUSTOM_METHOD",
                rel_path=str(entry["rel_path"]),
            ))
        for target_id in entry.get("frontend_computed_ids", []):
            traces.append(MiniAdminComponentTrace(
                screen_id=screen_id,
                component_id=component_id,
                component_selector=selector,
                source_file=source_file,
                line_number=line_number,
                target_id=str(target_id),
                target_type=(
                    config.mini_admin_sources.frontend_computed_type
                    if config.mini_admin_sources else "FRONTEND_COMPUTED"
                ),
                relation_type=(
                    config.mini_admin_sources.relation_type
                    if config.mini_admin_sources else "DEPENDS_ON"
                ),
                context="mini_admin_component_trace:FRONTEND_COMPUTED",
                rel_path=str(entry["rel_path"]),
            ))
    return traces


def build_mini_admin_component_trace_entries(
    root: Path,
    config: ProjectConfig,
) -> List[Dict[str, object]]:
    """Build graph-ba-owned runtime trace entries for mini-admin component ids."""
    if not config.mini_admin_sources:
        return []

    files = _collect_mini_admin_source_files(root, config)
    test_ids_by_ac = _collect_test_ids_by_ac(root, config)
    react_aliases = _collect_react_ui_aliases(root, config)
    entries: List[Dict[str, object]] = []
    for filepath in files:
        try:
            text = filepath.read_text(encoding="utf-8")
        except (UnicodeDecodeError, OSError):
            continue
        try:
            rel_path = str(filepath.relative_to(root))
        except ValueError:
            rel_path = str(filepath)
        screen_id = _mini_admin_screen_id(filepath, root, config)
        if not screen_id:
            continue
        constants_text = _read_sibling_ts_constants(filepath) + "\n" + text
        resource_constants = _extract_ts_resource_constants(constants_text)
        source_map = _extract_mini_admin_source_map(text, resource_constants)
        trace_path = filepath.with_name(config.mini_admin_sources.trace_filename)
        if not trace_path.is_file():
            continue
        try:
            raw_trace = json.loads(trace_path.read_text(encoding="utf-8"))
        except (json.JSONDecodeError, OSError, UnicodeDecodeError):
            continue
        if not isinstance(raw_trace, dict):
            continue
        try:
            trace_rel_path = str(trace_path.relative_to(root))
        except ValueError:
            trace_rel_path = str(trace_path)
        for selector, raw_entry in raw_trace.items():
            if str(selector).startswith("$") or not isinstance(raw_entry, dict):
                continue
            source_keys = _trace_source_keys(raw_entry)
            source_contracts = [_source for key in source_keys
                                for _source in [source_map.get(key)] if _source]
            ac_ids = _trace_string_array(raw_entry.get("acIds"))
            raw_ids = _trace_string_array(raw_entry.get("rawIds"))
            aliases = _component_aliases_for(str(selector), react_aliases)
            component_id = _component_id_for(str(selector), aliases, config)
            test_ids = sorted({
                test_id
                for ac_id in ac_ids
                for test_id in test_ids_by_ac.get(ac_id, set())
            } | set(_trace_string_array(raw_entry.get("testIds"))))
            entries.append({
                "screen_id": screen_id,
                "component_id": component_id,
                "selector": str(selector),
                "aliases": aliases,
                "source_keys": source_keys,
                "ac_ids": ac_ids,
                "raw_ids": raw_ids,
                "test_ids": test_ids,
                "trace_gap": str(raw_entry.get("traceGap") or ""),
                "resource_ids": sorted({
                    f"{config.mini_admin_sources.resource_type}:{resource}"
                    for source in source_contracts
                    for resource in source["resources"]
                }),
                "custom_method_ids": sorted({
                    f"{config.mini_admin_sources.custom_method_type}:{method}"
                    for source in source_contracts
                    for method in source["custom_methods"]
                }),
                "frontend_computed_ids": sorted({
                    _frontend_computed_id(screen_id, source_key, config)
                    for source_key in source_keys
                    for source in [source_map.get(source_key)]
                    if source and source.get("frontend_computed")
                }),
                "line_number": _line_number_for(text, str(selector)),
                "rel_path": trace_rel_path,
            })
    return entries


def export_mini_admin_component_trace_map(
    root: Path,
    config: ProjectConfig,
) -> Dict[str, Dict[str, Dict[str, object]]]:
    """Return mini-admin overlay trace maps grouped by screen family id."""
    grouped: Dict[str, Dict[str, Dict[str, object]]] = defaultdict(dict)
    for entry in build_mini_admin_component_trace_entries(root, config):
        screen_id = str(entry["screen_id"])
        payload = {
            "sources": entry.get("source_keys", []),
            "acIds": entry.get("ac_ids", []),
            "rawIds": entry.get("raw_ids", []),
            "testIds": entry.get("test_ids", []),
        }
        if entry.get("trace_gap"):
            payload["traceGap"] = entry["trace_gap"]
        keys = [str(entry["selector"]), *[str(alias) for alias in entry.get("aliases", [])]]
        for key in dict.fromkeys(keys):
            grouped[screen_id][key] = payload
    return {screen: dict(entries) for screen, entries in sorted(grouped.items())}


def _mini_admin_screen_id(filepath: Path, root: Path, config: ProjectConfig) -> str:
    if not config.mini_admin_sources:
        return ""
    try:
        parts = filepath.relative_to(root).parts
    except ValueError:
        parts = filepath.parts
    marker = config.mini_admin_sources.feature_path_segment
    if marker not in parts:
        return ""
    index = parts.index(marker)
    if index + 1 >= len(parts):
        return ""
    feature = parts[index + 1]
    screen_key = re.sub(r"[^A-Za-z0-9]+", "-", feature).strip("-").upper()
    return f"{config.mini_admin_sources.screen_family_prefix}{screen_key}" if screen_key else ""


def _collect_mini_admin_source_files(root: Path, config: ProjectConfig) -> List[Path]:
    if not config.mini_admin_sources:
        return []
    return _collect_configured_files(
        root,
        config.mini_admin_sources.dirs,
        config.mini_admin_sources.files,
        config.mini_admin_sources.extensions,
    )


def _collect_test_ids_by_ac(root: Path, config: ProjectConfig) -> Dict[str, Set[str]]:
    by_ac: Dict[str, Set[str]] = defaultdict(set)
    if not config.tests:
        return by_ac
    for ref in scan_test_references(root, config):
        test_id = f"TEST:{ref.rel_path}"
        for target_id in ref.target_ids:
            if classify_id(target_id, config) == "AC":
                by_ac[target_id].add(test_id)
    return by_ac


def _collect_react_ui_aliases(
    root: Path,
    config: ProjectConfig,
) -> Dict[str, Set[str]]:
    """Map ordinary data-testid selectors to UIC aliases found on the same JSX tag."""
    aliases: Dict[str, Set[str]] = defaultdict(set)
    if not config.react_ui:
        return aliases
    files = _collect_configured_files(
        root,
        config.react_ui.dirs,
        config.react_ui.files,
        config.react_ui.extensions,
    )
    attr_re = re.compile(
        r"(?P<prop>data-testid|data-test-id|testID|data-uic-id)\s*=\s*"
        r"(?:\"(?P<double>[^\"]+)\"|'(?P<single>[^']+)'|\{\s*\"(?P<braced_double>[^\"]+)\"\s*\}|\{\s*'(?P<braced_single>[^']+)'\s*\})"
    )
    for filepath in files:
        try:
            text = _mask_js_comments(filepath.read_text(encoding="utf-8"))
        except (UnicodeDecodeError, OSError):
            continue
        for tag in re.finditer(r"<[A-Za-z][^<>]*?>", text, flags=re.DOTALL):
            attrs: Dict[str, List[str]] = defaultdict(list)
            for match in attr_re.finditer(tag.group(0)):
                value = next(
                    item for item in (
                        match.group("double"),
                        match.group("single"),
                        match.group("braced_double"),
                        match.group("braced_single"),
                    )
                    if item is not None
                )
                attrs[match.group("prop")].append(value)
            uic_values = [
                value for value in attrs.get("data-uic-id", [])
                if classify_id(normalize_id(value, config), config) == "UIC"
            ]
            test_values = attrs.get("data-testid", []) + attrs.get("data-test-id", []) + attrs.get("testID", [])
            for test_id in test_values:
                for uic in uic_values:
                    normalized_uic = normalize_id(uic, config)
                    aliases[test_id].add(normalized_uic)
                    aliases[normalized_uic].add(test_id)
    return aliases


def _component_aliases_for(selector: str, aliases: Dict[str, Set[str]]) -> List[str]:
    return sorted(aliases.get(selector, set()))


def _component_id_for(
    selector: str,
    aliases: List[str],
    config: ProjectConfig,
) -> str:
    for alias in aliases:
        normalized = normalize_id(alias, config)
        if classify_id(normalized, config) == "UIC":
            return normalized
    normalized = normalize_id(selector, config)
    if classify_id(normalized, config) == "UIC":
        return normalized
    prefix = config.mini_admin_sources.component_fallback_prefix if config.mini_admin_sources else "UIC:"
    return f"{prefix}{selector}"


def _trace_source_keys(raw_entry: Dict[str, object]) -> List[str]:
    values: List[str] = []
    source = raw_entry.get("source")
    if isinstance(source, str):
        values.append(source)
    sources = raw_entry.get("sources")
    if isinstance(sources, list):
        values.extend(item for item in sources if isinstance(item, str))
    return list(dict.fromkeys(values))


def _trace_string_array(value: object) -> List[str]:
    if not isinstance(value, list):
        return []
    return [item for item in value if isinstance(item, str)]


def _extract_mini_admin_source_map(
    text: str,
    constants: Dict[str, Dict[str, str]],
) -> Dict[str, Dict[str, object]]:
    body = _extract_first_ts_sources_object(text)
    if not body:
        return {}
    source_map: Dict[str, Dict[str, object]] = {}
    for key, value in _split_top_level_object_entries(body).items():
        source_map[key] = {
            "resources": _extract_ts_resources(value, constants),
            "custom_methods": _extract_ts_custom_methods(value),
            "frontend_computed": _is_frontend_computed_source(value),
        }
    return source_map


def _is_frontend_computed_source(value: str) -> bool:
    return (
        "computedFrontendDataSource" in value
        or re.search(r"\bkind\s*:\s*[\"']computed-frontend[\"']", value) is not None
    )


def _frontend_computed_id(screen_id: str, source_key: str, config: ProjectConfig) -> str:
    node_type = (
        config.mini_admin_sources.frontend_computed_type
        if config.mini_admin_sources else "FRONTEND_COMPUTED"
    )
    safe_key = re.sub(r"[^A-Za-z0-9_.:-]+", "-", source_key).strip("-")
    return f"{node_type}:{screen_id}:{safe_key}"


def _extract_first_ts_sources_object(text: str) -> str:
    match = re.search(r"(?:export\s+)?const\s+\w*Sources\s*=\s*\{", text)
    if not match:
        return ""
    open_index = text.find("{", match.start())
    close_index = _find_matching_brace(text, open_index)
    if close_index < 0:
        return ""
    return text[open_index + 1:close_index]


def _split_top_level_object_entries(body: str) -> Dict[str, str]:
    entries: Dict[str, str] = {}
    index = 0
    while index < len(body):
        while index < len(body) and body[index] in " \t\r\n,":
            index += 1
        key_match = re.match(r"([A-Za-z_$][A-Za-z0-9_$]*)\s*:", body[index:])
        if not key_match:
            index += 1
            continue
        key = key_match.group(1)
        value_start = index + key_match.end()
        value_end = _find_top_level_comma_or_end(body, value_start)
        entries[key] = body[value_start:value_end].strip()
        index = value_end + 1
    return entries


def _find_matching_brace(text: str, open_index: int) -> int:
    depth = 0
    quote = ""
    escaped = False
    for index in range(open_index, len(text)):
        char = text[index]
        if quote:
            if escaped:
                escaped = False
            elif char == "\\":
                escaped = True
            elif char == quote:
                quote = ""
            continue
        if char in "\"'`":
            quote = char
        elif char == "{":
            depth += 1
        elif char == "}":
            depth -= 1
            if depth == 0:
                return index
    return -1


def _find_top_level_comma_or_end(text: str, start: int) -> int:
    depths = {"{": 0, "[": 0, "(": 0}
    quote = ""
    escaped = False
    for index in range(start, len(text)):
        char = text[index]
        if quote:
            if escaped:
                escaped = False
            elif char == "\\":
                escaped = True
            elif char == quote:
                quote = ""
            continue
        if char in "\"'`":
            quote = char
        elif char in depths:
            depths[char] += 1
        elif char == "}":
            if depths["{"] == 0 and depths["["] == 0 and depths["("] == 0:
                return index
            depths["{"] = max(0, depths["{"] - 1)
        elif char == "]":
            depths["["] = max(0, depths["["] - 1)
        elif char == ")":
            depths["("] = max(0, depths["("] - 1)
        elif char == "," and all(depth == 0 for depth in depths.values()):
            return index
    return len(text)


def _extract_ts_resource_constants(text: str) -> Dict[str, Dict[str, str]]:
    constants: Dict[str, Dict[str, str]] = {}
    pattern = re.compile(
        r"(?:export\s+)?const\s+([A-Z0-9_]*RESOURCES)\s*=\s*\{(?P<body>.*?)\}\s*as\s+const",
        re.DOTALL,
    )
    entry_pattern = re.compile(r"([A-Za-z0-9_]+)\s*:\s*[\"']([^\"']+)[\"']")
    for match in pattern.finditer(text):
        constants[match.group(1)] = {
            key: value for key, value in entry_pattern.findall(match.group("body"))
        }
    return constants


def _read_sibling_ts_constants(filepath: Path) -> str:
    chunks: List[str] = []
    for sibling_name in ("resources.ts", "resources.tsx"):
        sibling = filepath.with_name(sibling_name)
        if sibling == filepath or not sibling.is_file():
            continue
        try:
            chunks.append(sibling.read_text(encoding="utf-8"))
        except (UnicodeDecodeError, OSError):
            continue
    return "\n".join(chunks)


def _extract_ts_resources(text: str, constants: Dict[str, Dict[str, str]]) -> Set[str]:
    resources: Set[str] = set()
    for raw in re.findall(r"\bresource\s*:\s*([^,\n}]+)", text):
        value = _resolve_ts_resource_expr(raw, constants)
        if value:
            resources.add(value)
    for raw_array in re.findall(r"\bderivedFrom\s*:\s*\[(.*?)\]", text, flags=re.DOTALL):
        for raw_item in raw_array.split(","):
            value = _resolve_ts_resource_expr(raw_item, constants)
            if value and ":" not in value:
                resources.add(value)
    return resources


def _extract_ts_custom_methods(text: str) -> Set[str]:
    methods: Set[str] = set()
    for raw_array in re.findall(r"\bcustomMethods\s*:\s*\[(.*?)\]", text, flags=re.DOTALL):
        for value in re.findall(r"[\"']([^\"']+)[\"']", raw_array):
            if value:
                methods.add(value)
    for value in re.findall(r"\bcustomMethod\s*:\s*[\"']([^\"']+)[\"']", text):
        if value:
            methods.add(value)
    return methods


def _resolve_ts_resource_expr(raw: str, constants: Dict[str, Dict[str, str]]) -> str:
    expr = raw.strip().rstrip(",")
    literal = re.match(r"^[\"']([^\"']+)[\"']$", expr)
    if literal:
        return literal.group(1)
    attr = re.match(r"^([A-Z0-9_]*RESOURCES)\.([A-Za-z0-9_]+)$", expr)
    if attr:
        return constants.get(attr.group(1), {}).get(attr.group(2), "")
    return ""


def _line_number_for(text: str, needle: str) -> int:
    index = text.find(needle)
    if index < 0:
        return 0
    return text.count("\n", 0, index) + 1


def scan_react_ui_elements(
    root: Path,
    config: ProjectConfig,
) -> List[ReactUiElement]:
    """Scan React JSX UI trace attributes.

    This scanner intentionally imports only literal attribute values selected by
    `[react_ui]` patterns unless `include_unmatched=true`.
    """
    if not config.react_ui:
        return []

    files = _collect_configured_files(
        root,
        config.react_ui.dirs,
        config.react_ui.files,
        config.react_ui.extensions,
    )
    prop_roles = _react_ui_prop_roles(config)
    prop_re = "|".join(re.escape(prop) for prop in prop_roles)
    if not prop_re:
        return []
    attr_re = re.compile(
        rf"(?P<prop>{prop_re})\s*=\s*"
        r"(?:"
        r"\"(?P<double>[^\"]+)\""
        r"|'(?P<single>[^']+)'"
        r"|\{\s*\"(?P<braced_double>[^\"]+)\"\s*\}"
        r"|\{\s*'(?P<braced_single>[^']+)'\s*\}"
        r"|\{\s*`(?P<braced_template>[^`$]+)`\s*\}"
        r")"
    )
    component_include_res = [
        re.compile(pattern) for pattern in config.react_ui.include_patterns
    ]
    screen_include_res = [
        re.compile(pattern) for pattern in config.react_ui.screen_include_patterns
    ]
    screen_family_include_res = [
        re.compile(pattern)
        for pattern in config.react_ui.screen_family_include_patterns
    ]

    elements: List[ReactUiElement] = []
    for filepath in files:
        try:
            text = filepath.read_text(encoding="utf-8")
        except (UnicodeDecodeError, OSError):
            continue
        masked = _mask_js_comments(text)
        try:
            rel_path = str(filepath.relative_to(root))
        except ValueError:
            rel_path = str(filepath)
        source_id = f"REACT:{rel_path}"

        for match in attr_re.finditer(masked):
            selector = next(
                value for value in (
                    match.group("double"),
                    match.group("single"),
                    match.group("braced_double"),
                    match.group("braced_single"),
                    match.group("braced_template"),
                )
                if value is not None
            )
            role = prop_roles[match.group("prop")]
            if role == "screen_family":
                include_res = screen_family_include_res
                fallback_type = config.react_ui.screen_family_type
                relation_type = config.react_ui.screen_relation_type
            elif role == "screen":
                include_res = screen_include_res
                fallback_type = config.react_ui.screen_type
                relation_type = config.react_ui.screen_relation_type
            else:
                include_res = component_include_res
                fallback_type = config.react_ui.selector_type
                relation_type = config.react_ui.relation_type

            if not _react_selector_included(
                selector,
                include_res,
                config.react_ui.include_unmatched,
            ):
                continue

            normalized = normalize_id(selector, config)
            target_type = classify_id(normalized, config)
            target_id = normalized
            if target_type is None:
                if not config.react_ui.include_unmatched:
                    continue
                target_type = fallback_type
                target_id = f"{target_type}:{selector}"

            line_number = masked.count("\n", 0, match.start()) + 1
            elements.append(ReactUiElement(
                source_id=source_id,
                source_type=config.react_ui.source_type,
                source_file=filepath,
                line_number=line_number,
                selector=selector,
                target_id=target_id,
                target_type=target_type,
                relation_type=relation_type,
                role=role,
                context=f"{match.group('prop')}={selector}",
                rel_path=rel_path,
            ))
    return elements


def _react_ui_prop_roles(config: ProjectConfig) -> Dict[str, str]:
    if not config.react_ui:
        return {}
    roles: Dict[str, str] = {}
    for prop in config.react_ui.props:
        roles[prop] = "component"
    for prop in config.react_ui.screen_props:
        roles[prop] = "screen"
    for prop in config.react_ui.screen_family_props:
        roles[prop] = "screen_family"
    return roles


def _collect_configured_files(
    root: Path,
    dirs: List[str],
    files: List[str],
    extensions: List[str],
) -> List[Path]:
    collected: List[Path] = []
    for dir_str in dirs:
        d = root / dir_str
        if not d.exists():
            continue
        for ext in extensions:
            collected.extend(sorted(d.rglob(f"*.{ext}")))
    for pattern in files:
        collected.extend(sorted(root.glob(pattern)))
    seen: Set[Path] = set()
    result: List[Path] = []
    for item in collected:
        if item in seen or not item.is_file():
            continue
        seen.add(item)
        result.append(item)
    return result


def _react_selector_included(
    selector: str,
    include_res: List[re.Pattern],
    include_unmatched: bool,
) -> bool:
    if include_unmatched:
        return True
    return any(pattern.search(selector) for pattern in include_res)


def _mask_js_comments(text: str) -> str:
    """Replace JS/TS comments with spaces while preserving line offsets."""
    result: List[str] = []
    i = 0
    state = "normal"
    quote = ""
    while i < len(text):
        ch = text[i]
        nxt = text[i + 1] if i + 1 < len(text) else ""

        if state == "line_comment":
            if ch == "\n":
                state = "normal"
                result.append(ch)
            else:
                result.append(" ")
            i += 1
            continue

        if state == "block_comment":
            if ch == "*" and nxt == "/":
                result.extend("  ")
                state = "normal"
                i += 2
            else:
                result.append("\n" if ch == "\n" else " ")
                i += 1
            continue

        if state == "string":
            result.append(ch)
            if ch == "\\" and i + 1 < len(text):
                result.append(text[i + 1])
                i += 2
                continue
            if ch == quote:
                state = "normal"
            i += 1
            continue

        if ch in {"'", '"', "`"}:
            state = "string"
            quote = ch
            result.append(ch)
            i += 1
            continue
        if ch == "/" and nxt == "/":
            result.extend("  ")
            state = "line_comment"
            i += 2
            continue
        if ch == "/" and nxt == "*":
            result.extend("  ")
            state = "block_comment"
            i += 2
            continue
        result.append(ch)
        i += 1
    return "".join(result)


def _ast_call_name(func: ast.expr) -> str:
    if isinstance(func, ast.Name):
        return func.id
    if isinstance(func, ast.Attribute):
        return func.attr
    return ""


def _ast_kw_value(call: ast.Call, name: str) -> ast.expr | None:
    for kw in call.keywords:
        if kw.arg == name:
            return kw.value
    return None


def _ast_kw_string(call: ast.Call, name: str) -> str | None:
    value = _ast_kw_value(call, name)
    return value.value if isinstance(value, ast.Constant) and isinstance(value.value, str) else None


def _ast_string(value: ast.expr | None) -> str | None:
    if isinstance(value, ast.Constant) and isinstance(value.value, str):
        return value.value
    return None


def _ast_string_items(value: ast.expr | None) -> List[str]:
    if isinstance(value, (ast.Tuple, ast.List, ast.Set)):
        return [item.value for item in value.elts
                if isinstance(item, ast.Constant) and isinstance(item.value, str)]
    single = _ast_string(value)
    return [single] if single else []


def _extract_trace_links(value: ast.expr | None) -> List[Tuple[str, str]]:
    if value is None:
        return []
    if not isinstance(value, ast.Call):
        return []
    call_name = _ast_call_name(value.func)

    # Traceability.implements("AC-...")
    if (
        isinstance(value.func, ast.Attribute)
        and value.func.attr == "implements"
        and _ast_call_name(value.func.value) == "Traceability"
    ):
        artifacts = [
            artifact for artifact in (_ast_string(arg) for arg in value.args)
            if artifact is not None
        ]
        return [(artifact, "implements") for artifact in artifacts]

    if call_name != "Traceability":
        return []

    links: List[Tuple[str, str]] = []
    artifacts_value = _ast_kw_value(value, "artifacts")
    for artifact in _ast_string_items(artifacts_value):
        links.append((artifact, "implements"))

    links_value = _ast_kw_value(value, "links")
    if isinstance(links_value, (ast.Tuple, ast.List, ast.Set)):
        for item in links_value.elts:
            parsed = _extract_trace_link(item)
            if parsed:
                links.append(parsed)
    return links


def _extract_trace_link(value: ast.expr) -> Tuple[str, str] | None:
    if not isinstance(value, ast.Call) or _ast_call_name(value.func) != "TraceLink":
        return None
    artifact = _ast_kw_string(value, "artifact")
    if artifact is None and value.args:
        artifact = _ast_string(value.args[0])
    relation = _ast_kw_string(value, "relation")
    if relation is None and len(value.args) > 1:
        relation = _ast_string(value.args[1])
    if not artifact:
        return None
    return artifact, relation or "implements"


def _relation_type(raw: str) -> str:
    value = re.sub(r"[^A-Za-z0-9]+", "_", raw.strip()).strip("_").upper()
    return value or "IMPLEMENTS"


# ── Phase 3: Graph construction ──────────────────────────────────

def _find_owner(
    file_arts: List[Tuple[int, str]],
    ref_line: int,
) -> Optional[str]:
    if not file_arts:
        return None
    if len(file_arts) == 1:
        return file_arts[0][1]
    best = None
    for def_line, aid in file_arts:
        if def_line <= ref_line:
            best = aid
        else:
            break
    return best


def build_graph(
    registry: Dict[str, Artifact],
    references: List[Reference],
    config: ProjectConfig,
    index_xrefs: Optional[List[Tuple[str, str, Path, int]]] = None,
    code_refs: Optional[List[CodeReference]] = None,
    test_refs: Optional[List[CodeReference]] = None,
    ui_refs: Optional[List[CodeReference]] = None,
    mini_registry_traces: Optional[List[MiniRegistryTrace]] = None,
    react_ui_elements: Optional[List[ReactUiElement]] = None,
    mini_admin_source_traces: Optional[List[MiniAdminSourceTrace]] = None,
    mini_admin_component_traces: Optional[List[MiniAdminComponentTrace]] = None,
) -> nx.DiGraph:
    G = nx.DiGraph()

    for aid, art in registry.items():
        origin = config.types.get(art.artifact_type).origin if art.artifact_type in config.types else ""
        G.add_node(aid, type=art.artifact_type, title=art.title,
                   source_file=str(art.source_file.name), origin=origin)

    file_arts_map: Dict[Path, List[Tuple[int, str]]] = defaultdict(list)
    for aid, art in registry.items():
        file_arts_map[art.source_file].append((art.line_number, aid))
    for k in file_arts_map:
        file_arts_map[k].sort()

    for ref in references:
        target = ref.target_id
        if target not in G:
            atype = classify_id(target, config)
            origin = config.types.get(atype).origin if atype in config.types else ""
            G.add_node(target, type=atype or "UNKNOWN",
                       title="", source_file="", defined=False, origin=origin)

        file_arts = file_arts_map.get(ref.source_file)
        owner = _find_owner(file_arts, ref.line_number) if file_arts else None

        if owner and owner != target:
            G.add_edge(owner, target, context=ref.context,
                       source_file=str(ref.source_file.name),
                       line=ref.line_number,
                       relation_type="MENTIONS")
        elif not owner:
            file_node = f"FILE:{ref.source_file.name}"
            if not G.has_node(file_node):
                G.add_node(file_node, type="FILE", title=ref.source_file.name,
                           source_file=str(ref.source_file.name), defined=True,
                           origin="container")
            if target != file_node:
                G.add_edge(file_node, target, context=ref.context,
                           source_file=str(ref.source_file.name),
                           line=ref.line_number,
                           relation_type="MENTIONS")

    if index_xrefs:
        for src, tgt, fpath, lnum in index_xrefs:
            if tgt not in G:
                atype = classify_id(tgt, config)
                origin = config.types.get(atype).origin if atype in config.types else ""
                G.add_node(tgt, type=atype or "UNKNOWN",
                           title="", source_file="", defined=False, origin=origin)
            if src not in G:
                continue
            if src != tgt:
                G.add_edge(src, tgt, context="index_table",
                           source_file=str(fpath.name), line=lnum,
                           relation_type="INDEX")

    # ── Code references → CODE nodes, test references → TEST nodes,
    #    UI trace references → UI nodes ──
    _add_source_ref_nodes(G, code_refs, "CODE:", "CODE", config,
                          relation_type="CODE_TRACE", origin="implementation")
    _add_source_ref_nodes(G, test_refs, "TEST:", "TEST", config,
                          relation_type="TEST_EVIDENCE", origin="evidence")
    _add_source_ref_nodes(G, ui_refs, "UI:", "UI", config,
                          relation_type="UI_TRACE", origin="evidence")
    _add_mini_registry_nodes(G, mini_registry_traces, config)
    _add_react_ui_nodes(G, react_ui_elements, config)
    _add_mini_admin_source_nodes(G, mini_admin_source_traces, config)
    _add_mini_admin_component_trace_nodes(G, mini_admin_component_traces, config)

    for aid in registry:
        G.nodes[aid]["defined"] = True

    _resolve_dangling_variants(G, registry)

    return G


def _add_react_ui_nodes(
    G: nx.DiGraph,
    elements: Optional[List[ReactUiElement]],
    config: ProjectConfig,
):
    if not elements:
        return
    by_source: Dict[str, List[ReactUiElement]] = defaultdict(list)
    for element in elements:
        by_source[element.source_id].append(element)
        origin = config.react_ui.origin if config.react_ui else "implementation"
        if not G.has_node(element.source_id):
            G.add_node(element.source_id, type=element.source_type, title=element.rel_path,
                       source_file=element.rel_path, defined=True, origin=origin)

        if element.target_id not in G:
            target_origin = (
                config.types.get(element.target_type).origin
                if element.target_type in config.types
                else origin
            )
            G.add_node(element.target_id, type=element.target_type, title=element.selector,
                       source_file=element.rel_path, defined=True, origin=target_origin)

        G.add_edge(element.source_id, element.target_id,
                   context=element.context,
                   source_file=element.rel_path,
                   line=element.line_number,
                   relation_type=element.relation_type)

    for source_elements in by_source.values():
        _add_react_ui_ownership_edges(G, source_elements, config)


def _add_react_ui_ownership_edges(
    G: nx.DiGraph,
    elements: List[ReactUiElement],
    config: ProjectConfig,
):
    families = [e for e in elements if e.role == "screen_family"]
    screens = [e for e in elements if e.role == "screen"]
    components = [e for e in elements if e.role == "component"]
    if not config.react_ui:
        return

    for family in families:
        for screen in screens:
            if family.target_id == screen.target_id:
                continue
            G.add_edge(family.target_id, screen.target_id,
                       context="same React source",
                       source_file=screen.rel_path,
                       line=screen.line_number,
                       relation_type=config.react_ui.screen_family_relation_type)

    owners = screens if screens else families
    for owner in owners:
        for component in components:
            if owner.target_id == component.target_id:
                continue
            G.add_edge(owner.target_id, component.target_id,
                       context="same React source",
                       source_file=component.rel_path,
                       line=component.line_number,
                       relation_type=config.react_ui.screen_component_relation_type)


def _add_mini_registry_nodes(
    G: nx.DiGraph,
    traces: Optional[List[MiniRegistryTrace]],
    config: ProjectConfig,
):
    if not traces:
        return
    for trace in traces:
        if not G.has_node(trace.source_id):
            origin = config.mini_registry.origin if config.mini_registry else "implementation"
            G.add_node(trace.source_id, type=trace.source_type, title=trace.title,
                       source_file=trace.rel_path, defined=True, origin=origin)
        if not trace.target_id:
            continue
        if trace.target_id not in G:
            atype = classify_id(trace.target_id, config)
            target_origin = config.types.get(atype).origin if atype in config.types else ""
            G.add_node(trace.target_id, type=atype or "UNKNOWN",
                       title="", source_file="", defined=False,
                       origin=target_origin)
        G.add_edge(trace.source_id, trace.target_id,
                   context=trace.context,
                   source_file=trace.rel_path,
                   line=trace.line_number,
                   relation_type=trace.relation_type)


def _add_mini_admin_source_nodes(
    G: nx.DiGraph,
    traces: Optional[List[MiniAdminSourceTrace]],
    config: ProjectConfig,
):
    if not traces:
        return
    for trace in traces:
        origin = (
            config.mini_admin_sources.origin
            if config.mini_admin_sources
            else "implementation"
        )
        if not G.has_node(trace.source_id):
            G.add_node(trace.source_id, type=trace.source_type, title=trace.title,
                       source_file=trace.rel_path, defined=True, origin=origin)
        if not G.has_node(trace.target_id):
            G.add_node(trace.target_id, type=trace.target_type, title=trace.target_id,
                       source_file=trace.rel_path, defined=True, origin=origin)
        G.add_edge(trace.source_id, trace.target_id,
                   context=trace.context,
                   source_file=trace.rel_path,
                   line=trace.line_number,
                   relation_type=trace.relation_type)


def _add_mini_admin_component_trace_nodes(
    G: nx.DiGraph,
    traces: Optional[List[MiniAdminComponentTrace]],
    config: ProjectConfig,
):
    if not traces:
        return
    origin = (
        config.mini_admin_sources.origin
        if config.mini_admin_sources
        else "implementation"
    )
    component_type = (
        config.mini_admin_sources.component_type
        if config.mini_admin_sources
        else "UIC"
    )
    component_relation_type = (
        config.mini_admin_sources.component_relation_type
        if config.mini_admin_sources
        else "CONTAINS"
    )
    seen_containment: Set[Tuple[str, str]] = set()
    for trace in traces:
        if not G.has_node(trace.screen_id):
            screen_type = classify_id(trace.screen_id, config) or "SCREEN_FAMILY"
            G.add_node(trace.screen_id, type=screen_type, title=trace.screen_id,
                       source_file=trace.rel_path, defined=True, origin=origin)
        if not G.has_node(trace.component_id):
            G.add_node(trace.component_id, type=component_type, title=trace.component_selector,
                       source_file=trace.rel_path, defined=True, origin=origin)
        containment_key = (trace.screen_id, trace.component_id)
        if containment_key not in seen_containment:
            G.add_edge(trace.screen_id, trace.component_id,
                       context="mini_admin_component_trace",
                       source_file=trace.rel_path,
                       line=trace.line_number,
                       relation_type=component_relation_type)
            seen_containment.add(containment_key)
        if not G.has_node(trace.target_id):
            G.add_node(trace.target_id, type=trace.target_type, title=trace.target_id,
                       source_file=trace.rel_path, defined=True, origin=origin)
        G.add_edge(trace.component_id, trace.target_id,
                   context=trace.context,
                   source_file=trace.rel_path,
                   line=trace.line_number,
                   relation_type=trace.relation_type)


def _add_source_ref_nodes(
    G: nx.DiGraph,
    refs: Optional[List[CodeReference]],
    prefix: str,
    node_type: str,
    config: ProjectConfig,
    relation_type: str,
    origin: str,
):
    """Add meta-nodes (CODE:/TEST:) with edges to referenced artifacts."""
    if not refs:
        return
    for cref in refs:
        node_id = f"{prefix}{cref.rel_path}"
        if not G.has_node(node_id):
            G.add_node(node_id, type=node_type, title=cref.rel_path,
                       source_file=cref.rel_path, defined=True,
                       origin=origin)
        for target_id in cref.target_ids:
            if target_id not in G:
                atype = classify_id(target_id, config)
                target_origin = config.types.get(atype).origin if atype in config.types else ""
                G.add_node(target_id, type=atype or "UNKNOWN",
                           title="", source_file="", defined=False,
                           origin=target_origin)
            G.add_edge(node_id, target_id,
                       context=cref.context,
                       source_file=cref.rel_path,
                       line=cref.line_number,
                       relation_type=relation_type)


def _resolve_dangling_variants(G: nx.DiGraph, registry: Dict[str, Artifact]):
    """If an ID is referenced but not defined, link to its variants if they exist.

    E.g. BP-01 → BP-01a, BP-01b.
    """
    dangling = [
        n for n in G.nodes()
        if not G.nodes[n].get("defined", False) and not n.startswith("FILE:")
    ]
    for node_id in dangling:
        variants = [aid for aid in registry if aid.startswith(node_id) and aid != node_id]
        if not variants:
            continue
        preds = list(G.predecessors(node_id))
        for pred in preds:
            edge_data = G.edges[pred, node_id]
            for var in variants:
                if pred != var:
                    G.add_edge(pred, var, **edge_data)
        succs = list(G.successors(node_id))
        for succ in succs:
            edge_data = G.edges[node_id, succ]
            for var in variants:
                if var != succ:
                    G.add_edge(var, succ, **edge_data)
        G.remove_node(node_id)


# ── Phase 4: Verification checks ────────────────────────────────

@dataclass
class TraceReport:
    registry_count: Dict[str, int] = field(default_factory=dict)
    total_edges: int = 0
    orphans: List[str] = field(default_factory=list)
    dangling: List[Tuple[str, str, int]] = field(default_factory=list)
    coverage: Dict[str, dict] = field(default_factory=dict)
    missing_expected: List[Tuple[str, str]] = field(default_factory=list)


def verify(
    G: nx.DiGraph,
    registry: Dict[str, Artifact],
    references: List[Reference],
    config: ProjectConfig,
) -> TraceReport:
    report = TraceReport()

    type_counts: Dict[str, int] = defaultdict(int)
    for art in registry.values():
        type_counts[art.artifact_type] += 1
    report.registry_count = dict(type_counts)
    report.total_edges = G.number_of_edges()

    for aid in registry:
        if G.in_degree(aid) == 0:
            report.orphans.append(aid)

    defined_ids = set(registry.keys())
    dangling_ids: Set[str] = set()
    for ref in references:
        if ref.target_id not in defined_ids:
            if ref.target_id in G:
                continue
            dangling_ids.add(ref.target_id)

    dangling_first: Dict[str, Tuple[str, int]] = {}
    for ref in references:
        if ref.target_id in dangling_ids and ref.target_id not in dangling_first:
            dangling_first[ref.target_id] = (str(ref.source_file.name), ref.line_number)
    for did, (fname, lnum) in sorted(dangling_first.items()):
        report.dangling.append((did, fname, lnum))

    # Coverage matrix from config
    for cp in config.coverage_pairs:
        src_type, tgt_type, label = cp.source, cp.target, cp.label
        src_ids = [aid for aid, art in registry.items() if art.artifact_type == src_type]
        linked = []
        missing = []
        for sid in src_ids:
            if sid in G:
                has_link = any(
                    G.nodes.get(t, {}).get("type") == tgt_type
                    for t in G.successors(sid)
                )
                if has_link:
                    linked.append(sid)
                else:
                    missing.append(sid)
            else:
                missing.append(sid)
        total = len(src_ids)
        pct = (len(linked) / total * 100) if total > 0 else 0
        report.coverage[label] = {
            "total": total,
            "linked": len(linked),
            "pct": round(pct, 1),
            "missing": missing,
        }

    # Missing expected links from config
    for atype, expected in config.expected_cross_layer.items():
        for aid, art in registry.items():
            if art.artifact_type != atype or aid not in G:
                continue
            for target_type, label in expected:
                if not any(G.nodes.get(t, {}).get("type") == target_type
                           for t in G.successors(aid)):
                    report.missing_expected.append((aid, f"{target_type} ({label})"))

    return report


# ── Output: Console report ───────────────────────────────────────

def print_report(report: TraceReport, registry: Dict[str, Artifact],
                 config: ProjectConfig, verbose: bool):
    print("=" * 60)
    print("  Traceability Report")
    print(f"  Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}")
    print("=" * 60)

    print("\n--- Registry Summary ---")
    total = 0
    for tid in config.type_order:
        cnt = report.registry_count.get(tid, 0)
        total += cnt
        label = config.types[tid].label if tid in config.types else tid
        print(f"  {label:40s} {cnt:>4d}")
    # Types not in config (shouldn't happen, but be safe)
    for tid, cnt in report.registry_count.items():
        if tid not in config.type_order:
            print(f"  {tid:40s} {cnt:>4d}")
            total += cnt
    print(f"  {'TOTAL':40s} {total:>4d} artifacts, {report.total_edges} edges")

    print("\n--- Coverage Matrix ---")
    for label, data in report.coverage.items():
        status = "OK" if data["pct"] >= 100 else f"WARN: {len(data['missing'])} missing"
        bar = f"{data['linked']}/{data['total']} ({data['pct']}%)"
        print(f"  {label:25s} {bar:>20s}  [{status}]")
        if verbose and data["missing"]:
            for mid in data["missing"]:
                print(f"       - {mid}")

    if report.dangling:
        print(f"\n--- Dangling References ({len(report.dangling)}) ---")
        for did, fname, lnum in report.dangling:
            print(f"  [ERROR] {did} referenced in {fname}:{lnum} but NOT defined")
    else:
        print("\n--- Dangling References: none ---")

    if report.orphans:
        print(f"\n--- Orphan Artifacts ({len(report.orphans)}) ---")
        orphan_types = defaultdict(list)
        for oid in report.orphans:
            if oid in registry:
                orphan_types[registry[oid].artifact_type].append(oid)
        for tval, ids in sorted(orphan_types.items()):
            print(f"  [{tval}] ({len(ids)}): {', '.join(sorted(ids))}")
    else:
        print("\n--- Orphan Artifacts: none ---")

    if report.missing_expected:
        print(f"\n--- Missing Expected Links ({len(report.missing_expected)}) ---")
        for aid, missing_type in sorted(report.missing_expected):
            print(f"  [WARN] {aid} has no link to {missing_type}")
    else:
        print("\n--- Missing Expected Links: none ---")

    errors = len(report.dangling)
    warnings = len(report.orphans) + len(report.missing_expected)
    ok_pairs = sum(1 for d in report.coverage.values() if d["pct"] >= 100)
    print(f"\n{'=' * 60}")
    print(f"  {errors} errors, {warnings} warnings, "
          f"{ok_pairs}/{len(report.coverage)} coverage pairs at 100%")
    print(f"{'=' * 60}")


# ── Output: JSON export ──────────────────────────────────────────

def export_json(G: nx.DiGraph, registry: Dict[str, Artifact],
                report: TraceReport, path: Path):
    data = {
        "metadata": {
            "generated": datetime.now().isoformat(),
            "artifact_count": len(registry),
            "edge_count": G.number_of_edges(),
        },
        "nodes": [
            {
                "id": n,
                "type": d.get("type", ""),
                "origin": d.get("origin", ""),
                "title": d.get("title", ""),
                "source_file": d.get("source_file", ""),
                "defined": d.get("defined", False),
            }
            for n, d in G.nodes(data=True)
        ],
        "edges": [
            {
                "source": u,
                "target": v,
                "relation_type": d.get("relation_type", "MENTIONS"),
                "context": d.get("context", ""),
                "source_file": d.get("source_file", ""),
                "line": d.get("line", 0),
            }
            for u, v, d in G.edges(data=True)
        ],
        "report": {
            "dangling": [{"id": d, "file": f, "line": l} for d, f, l in report.dangling],
            "orphans": report.orphans,
            "coverage": report.coverage,
            "missing_expected": [{"id": a, "missing": m} for a, m in report.missing_expected],
        },
    }
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, ensure_ascii=False, indent=2), encoding="utf-8")
    print(f"\nJSON exported to {path}")


# ── Output: DOT export ───────────────────────────────────────────

# Default colors for common types; config can extend/override
_DEFAULT_COLORS = {
    "ST":      {"bg": "#FFF3C4", "border": "#D69E2E"},
    "BR":      {"bg": "#C3DAF9", "border": "#2B6CB0"},
    "BR_REQ":  {"bg": "#C3DAF9", "border": "#2B6CB0"},
    "BRL":     {"bg": "#FCCFCF", "border": "#C53030"},
    "BR_RULE": {"bg": "#FCCFCF", "border": "#C53030"},
    "BP":      {"bg": "#C6F6D5", "border": "#276749"},
    "BD":      {"bg": "#FEEBC8", "border": "#C05621"},
    "BF":      {"bg": "#E9D8FD", "border": "#6B46C1"},
    "F":       {"bg": "#B2F5EA", "border": "#285E61"},
    "VAD":     {"bg": "#FED7E2", "border": "#B83280"},
    "M":       {"bg": "#E2E8F0", "border": "#4A5568"},
    "DM":      {"bg": "#D6BCFA", "border": "#553C9A"},
    "SM":      {"bg": "#FBD38D", "border": "#B7791F"},
    "EN":      {"bg": "#BEE3F8", "border": "#2A69AC"},
    "RL":      {"bg": "#C6F6D5", "border": "#22543D"},
    "FILE":    {"bg": "#F7FAFC", "border": "#A0AEC0"},
    "CODE":    {"bg": "#E6FFFA", "border": "#319795"},
    "TEST":    {"bg": "#FAF5FF", "border": "#805AD5"},
    "UNKNOWN": {"bg": "#FED7D7", "border": "#E53E3E"},
}

_DEFAULT_SHAPES = {
    "ST": "house", "BR": "box", "BR_REQ": "box", "BRL": "octagon", "BR_RULE": "octagon",
    "BP": "cds", "BD": "diamond", "BF": "component",
    "F": "note", "VAD": "hexagon", "M": "box3d",
    "DM": "box", "SM": "box", "EN": "box", "RL": "box",
    "FILE": "folder", "UNKNOWN": "plaintext",
}

_HTML_SHAPES = {
    "ST": "triangle", "BR": "box", "BR_REQ": "box", "BRL": "diamond", "BR_RULE": "diamond",
    "BP": "ellipse", "BD": "hexagon", "BF": "box",
    "F": "star", "VAD": "hexagon", "M": "database",
    "DM": "box", "SM": "box", "EN": "box", "RL": "box",
    "FILE": "text", "UNKNOWN": "dot",
}

_HTML_SIZES = {
    "ST": 25, "BR": 18, "BR_REQ": 18, "BRL": 16, "BR_RULE": 16, "BP": 22, "BD": 20,
    "BF": 14, "F": 24, "VAD": 22, "M": 26,
    "DM": 16, "SM": 16, "EN": 14, "RL": 16,
    "FILE": 10, "UNKNOWN": 10,
}


def _get_colors(atype: str) -> dict:
    return _DEFAULT_COLORS.get(atype, _DEFAULT_COLORS["UNKNOWN"])


def export_dot(G: nx.DiGraph, config: ProjectConfig, path: Path):
    """Export graph as a richly styled DOT file with clusters."""
    type_groups: Dict[str, List[str]] = defaultdict(list)
    for n, d in G.nodes(data=True):
        atype = d.get("type", "UNKNOWN")
        type_groups[atype].append(n)

    lines: List[str] = []
    lines.append('digraph traceability {')
    lines.append('  rankdir=TB; newrank=true; concentrate=true; compound=true;')
    lines.append('  splines=ortho; nodesep=0.4; ranksep=0.8;')
    lines.append('  fontname="Helvetica"; bgcolor="#FAFAFA"; pad=0.5;')
    lines.append('  node [style="filled,rounded", fontname="Helvetica", fontsize=10, '
                 'penwidth=1.5, margin="0.15,0.08"];')
    lines.append('  edge [fontname="Helvetica", fontsize=8, penwidth=0.8, '
                 'arrowsize=0.7, color="#718096"];')
    lines.append('')

    # Clustered subgraphs by type order from config
    all_types = list(config.type_order) + [t for t in type_groups if t not in config.type_order]
    for atype in all_types:
        nodes = type_groups.get(atype, [])
        if not nodes:
            continue
        label = config.types[atype].label if atype in config.types else atype
        colors = _get_colors(atype)
        shape = _DEFAULT_SHAPES.get(atype, "box")
        nodes.sort()

        is_meta = atype in ("FILE", "UNKNOWN")
        style = 'rounded,dashed' if is_meta else 'rounded,filled'

        lines.append(f'  subgraph cluster_{atype} {{')
        lines.append(f'    label="{label}"; style="{style}";')
        lines.append(f'    fillcolor="{colors["bg"]}20"; color="{colors["border"]}";')
        lines.append(f'    penwidth=1.5; fontname="Helvetica"; fontsize=12;')
        for n in nodes:
            d = G.nodes[n]
            lbl = _dot_node_label(n, d)
            defined = d.get("defined", True)
            ns = "filled,rounded,dashed" if not defined else "filled,rounded"
            lines.append(
                f'    "{_esc(n)}" [label="{lbl}", shape={shape}, '
                f'fillcolor="{colors["bg"]}", color="{colors["border"]}", style="{ns}"];'
            )
        lines.append('  }')
        lines.append('')

    # Edges
    lines.append('  // Edges')
    for u, v, d in G.edges(data=True):
        src_type = G.nodes[u].get("type", "UNKNOWN") if u in G.nodes else "UNKNOWN"
        edge_color = _get_colors(src_type)["border"]
        rel = d.get("relation_type", "MENTIONS")
        ctx = d.get("context", "").replace('"', '\\"')[:60]
        tooltip = f"{rel}: {ctx}" if ctx else rel
        lines.append(
            f'  "{_esc(u)}" -> "{_esc(v)}" '
            f'[color="{edge_color}80", label="{rel if rel != "MENTIONS" else ""}", '
            f'tooltip="{tooltip}"];'
        )
    lines.append('}')

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines), encoding="utf-8")
    print(f"DOT exported to {path}")


def _esc(s: str) -> str:
    return s.replace('"', '\\"')


def _dot_node_label(node_id: str, data: dict) -> str:
    eid = node_id.replace('"', '\\"')
    title = data.get("title", "")
    if not title:
        return eid
    short = title[:35].replace('"', '\\"')
    if len(title) > 35:
        short += "…"
    return f"{eid}\\n{short}"


# ── Output: ARTIFACT_INDEX.md ────────────────────────────────────

def export_index(G: nx.DiGraph, registry: Dict[str, Artifact],
                 config: ProjectConfig, root: Path, path: Path):
    """Generate compact ARTIFACT_INDEX.md for agent navigation."""
    lines_out = [
        "# Artifact Index",
        "",
        f"Generated: {datetime.now().strftime('%Y-%m-%d')}. "
        "Rebuild: `graph-ba import`",
        "",
        "## Semantic Map",
        "",
    ]

    for topic, ids in config.clusters.items():
        existing = [i for i in ids if normalize_id(i, config) in registry]
        if existing:
            lines_out.append(f"**{topic}:** {', '.join(existing)}")

    lines_out.append("")
    lines_out.append("---")
    lines_out.append("")

    for tid in config.type_order:
        arts = sorted(
            [(aid, art) for aid, art in registry.items() if art.artifact_type == tid],
            key=lambda x: x[0],
        )
        if not arts:
            continue

        label = config.types[tid].label if tid in config.types else tid
        lines_out.append(f"## {label} ({len(arts)})")
        lines_out.append("")

        dir_groups: Dict[str, List[Tuple[str, Artifact]]] = defaultdict(list)
        for aid, art in arts:
            try:
                d = str(art.source_file.parent.relative_to(root))
            except ValueError:
                d = str(art.source_file.parent)
            dir_groups[d].append((aid, art))

        for dirpath, group in dir_groups.items():
            if len(dir_groups) > 1:
                lines_out.append(f"_{dirpath}/_")
            for aid, art in group:
                fname = art.source_file.name
                title = art.title[:55] if art.title else ""
                if title:
                    lines_out.append(f"- `{aid}` {fname}:{art.line_number} — {title}")
                else:
                    lines_out.append(f"- `{aid}` {fname}:{art.line_number}")

        lines_out.append("")

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines_out), encoding="utf-8")
    print(f"Index exported to {path}")


# ── Output: Interactive HTML (vis-network) ───────────────────────

def export_html(G: nx.DiGraph, config: ProjectConfig, path: Path):
    """Export a standalone interactive HTML visualization."""
    nodes_js: List[str] = []
    for n, d in G.nodes(data=True):
        atype = d.get("type", "UNKNOWN")
        title_text = d.get("title", "").replace("'", "\\'").replace("\n", " ")
        source_file = d.get("source_file", "")
        origin = d.get("origin", "")
        defined = d.get("defined", True)

        colors = _get_colors(atype)
        shape = _HTML_SHAPES.get(atype, "dot")
        size = _HTML_SIZES.get(atype, 15)
        group_label = config.types[atype].label if atype in config.types else atype

        in_deg = G.in_degree(n)
        out_deg = G.out_degree(n)
        tip_parts = [f"<b>{n}</b>"]
        if title_text:
            tip_parts.append(title_text)
        tip_parts.append(f"<i>Type:</i> {group_label}")
        if origin:
            tip_parts.append(f"<i>Origin:</i> {origin}")
        if source_file:
            tip_parts.append(f"<i>File:</i> {source_file}")
        tip_parts.append(f"<i>In:</i> {in_deg} | <i>Out:</i> {out_deg}")
        if not defined:
            tip_parts.append("<b style='color:red'>Not defined</b>")
        tooltip = "<br>".join(tip_parts).replace("'", "\\'")

        bg = colors["bg"] if defined else "#FED7D7"
        border = colors["border"] if defined else "#E53E3E"
        esc_n = n.replace("'", "\\'")

        nodes_js.append(
            f"  {{id:'{esc_n}',label:'{esc_n}',title:'{tooltip}',"
            f"shape:'{shape}',size:{size},group:'{atype}',"
            f"color:{{background:'{bg}',border:'{border}',"
            f"highlight:{{background:'{bg}',border:'{border}'}}}}}}"
        )

    edges_js: List[str] = []
    for u, v, d in G.edges(data=True):
        ctx = d.get("context", "").replace("'", "\\'")[:60]
        rel = d.get("relation_type", "MENTIONS")
        src_file = d.get("source_file", "").replace("'", "\\'")
        tip = f"{u} → {v}\\n{rel}"
        if ctx:
            tip += f"\\n{ctx}"
        if src_file:
            tip += f"\\n({src_file})"
        tip = tip.replace("'", "\\'")
        eu = u.replace("'", "\\'")
        ev = v.replace("'", "\\'")
        edges_js.append(f"  {{from:'{eu}',to:'{ev}',title:'{tip}'}}")

    # Legend items from config types
    legend_items_html = []
    for tid in config.type_order:
        if tid not in config.types:
            continue
        c = _get_colors(tid)
        lbl = config.types[tid].label
        legend_items_html.append(
            f'<label style="display:flex;align-items:center;gap:6px;margin:2px 0;cursor:pointer">'
            f'<input type="checkbox" checked data-group="{tid}" '
            f'onchange="toggleGroup(this)">'
            f'<span style="display:inline-block;width:14px;height:14px;'
            f'background:{c["bg"]};border:2px solid {c["border"]};border-radius:3px"></span>'
            f'<span style="font-size:11px;color:#4A5568">{lbl}</span></label>'
        )

    html = _HTML_TEMPLATE.format(
        nodes_data=",\n".join(nodes_js),
        edges_data=",\n".join(edges_js),
        legend_items="\n".join(legend_items_html),
        node_count=G.number_of_nodes(),
        edge_count=G.number_of_edges(),
    )

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(html, encoding="utf-8")
    print(f"HTML exported to {path}")


_HTML_TEMPLATE = """\
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Graph BA — Artifact Traceability</title>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/vis-network/9.1.2/dist/dist/vis-network.min.css" crossorigin="anonymous"/>
<script src="https://cdnjs.cloudflare.com/ajax/libs/vis-network/9.1.2/dist/vis-network.min.js" crossorigin="anonymous"></script>
<style>
  * {{ margin:0; padding:0; box-sizing:border-box; }}
  body {{ font-family: Helvetica, Arial, sans-serif; background: #FAFAFA; overflow: hidden; }}
  #graph {{ width:100vw; height:100vh; }}
  #legend {{
    position:fixed; top:12px; left:12px; z-index:9999;
    background:white; border:1px solid #CBD5E0; border-radius:8px;
    padding:10px 14px; box-shadow:0 2px 8px rgba(0,0,0,0.12);
    max-width:220px; max-height:90vh; overflow-y:auto;
  }}
  #legend h3 {{ font-size:13px; color:#2D3748; margin-bottom:6px; }}
  #stats {{
    position:fixed; bottom:12px; left:12px; z-index:9999;
    background:white; border:1px solid #CBD5E0; border-radius:8px;
    padding:8px 12px; box-shadow:0 2px 8px rgba(0,0,0,0.08);
    font-size:11px; color:#4A5568;
  }}
  #search {{
    position:fixed; top:12px; right:12px; z-index:9999;
    background:white; border:1px solid #CBD5E0; border-radius:8px;
    padding:8px 12px; box-shadow:0 2px 8px rgba(0,0,0,0.08);
  }}
  #search input {{
    border:1px solid #CBD5E0; border-radius:4px; padding:5px 8px;
    font-size:12px; width:200px; outline:none;
  }}
  #search input:focus {{ border-color:#4299E1; }}
  #stabilize-msg {{
    position:fixed; top:50%; left:50%; transform:translate(-50%,-50%);
    background:rgba(45,55,72,0.85); color:white; padding:16px 28px;
    border-radius:10px; font-size:14px; z-index:99999;
    transition: opacity 0.5s;
  }}
</style>
</head>
<body>
<div id="graph"></div>
<div id="legend">
  <h3>Legend (click to filter)</h3>
  {legend_items}
</div>
<div id="search">
  <input type="text" id="searchBox" placeholder="Search by ID..." oninput="onSearch(this.value)">
</div>
<div id="stats">Nodes: {node_count} | Edges: {edge_count}</div>
<div id="stabilize-msg">Stabilizing graph…</div>
<script>
var allNodes = new vis.DataSet([
{nodes_data}
]);
var allEdges = new vis.DataSet([
{edges_data}
]);
var container = document.getElementById('graph');
var data = {{ nodes: allNodes, edges: allEdges }};
var options = {{
  physics: {{
    enabled: true,
    barnesHut: {{
      gravitationalConstant: -6000, centralGravity: 0.25,
      springLength: 140, springConstant: 0.04, damping: 0.09, avoidOverlap: 0.4
    }},
    stabilization: {{ enabled: true, iterations: 500, updateInterval: 25 }}
  }},
  interaction: {{
    hover: true, tooltipDelay: 100,
    navigationButtons: true, keyboard: {{ enabled: true }}
  }},
  edges: {{
    arrows: {{ to: {{ enabled: true, scaleFactor: 0.5 }} }},
    smooth: {{ type: 'cubicBezier', forceDirection: 'vertical', roundness: 0.4 }},
    color: {{ inherit: 'from', opacity: 0.35 }}, width: 0.7, hoverWidth: 2
  }},
  nodes: {{
    font: {{ size: 11, face: 'Helvetica, Arial, sans-serif' }},
    borderWidth: 2, borderWidthSelected: 3
  }}
}};
var network = new vis.Network(container, data, options);
network.on('stabilizationIterationsDone', function() {{
  network.setOptions({{ physics: {{ enabled: false }} }});
  document.getElementById('stabilize-msg').style.opacity = '0';
  setTimeout(function() {{
    document.getElementById('stabilize-msg').style.display = 'none';
  }}, 600);
}});
function onSearch(q) {{
  q = q.trim().toUpperCase();
  if (!q) {{
    allNodes.forEach(function(n) {{ allNodes.update({{id:n.id, opacity:1, font:{{size:11}}}}); }});
    return;
  }}
  allNodes.forEach(function(n) {{
    var match = n.id.toUpperCase().indexOf(q) >= 0;
    allNodes.update({{id:n.id, opacity: match ? 1 : 0.15, font:{{size: match ? 14 : 8}}}});
  }});
}}
var origNodes = {{}};
allNodes.forEach(function(n) {{ origNodes[n.id] = JSON.parse(JSON.stringify(n)); }});
var hiddenGroups = {{}};
function toggleGroup(cb) {{
  var g = cb.dataset.group;
  if (cb.checked) {{ delete hiddenGroups[g]; }} else {{ hiddenGroups[g] = true; }}
  var updates = [];
  allNodes.forEach(function(n) {{
    if (n.group === g) {{
      if (cb.checked) {{
        var o = origNodes[n.id];
        updates.push({{id:n.id, hidden:false, color:o.color, shape:o.shape, size:o.size}});
      }} else {{
        updates.push({{id:n.id, hidden:true}});
      }}
    }}
  }});
  allNodes.update(updates);
}}
</script>
</body>
</html>
"""


def _filter_graph(G: nx.DiGraph, no_file_nodes: bool, no_transitive: bool,
                  verbose: bool) -> nx.DiGraph:
    """Return a filtered copy of G for visualization."""
    if not no_file_nodes and not no_transitive:
        return G

    H = G.copy()
    removed_nodes = 0
    removed_edges = 0

    if no_file_nodes:
        file_nodes = [n for n, d in H.nodes(data=True) if d.get("type") == "FILE"]
        H.remove_nodes_from(file_nodes)
        removed_nodes = len(file_nodes)

    if no_transitive:
        to_remove = []
        for u, v in list(H.edges()):
            H.remove_edge(u, v)
            if nx.has_path(H, u, v):
                to_remove.append((u, v))
            else:
                H.add_edge(u, v, **G.edges[u, v])
        for u, v in to_remove:
            if H.has_edge(u, v):
                H.remove_edge(u, v)
        removed_edges = len(to_remove)

    if verbose or (removed_nodes or removed_edges):
        orig_n, orig_e = G.number_of_nodes(), G.number_of_edges()
        new_n, new_e = H.number_of_nodes(), H.number_of_edges()
        print(f"\n[filter] {orig_n} → {new_n} nodes, {orig_e} → {new_e} edges"
              f" (removed {removed_nodes} FILE nodes, {removed_edges} transitive edges)")

    return H


# ── CLI ───────────────────────────────────────────────────────────

@click.command()
@click.option("--root", type=click.Path(exists=True, path_type=Path),
              default=".", help="Project root directory")
@click.option("--json-out", type=click.Path(path_type=Path), default=None,
              help="Path for JSON graph export")
@click.option("--dot-out", type=click.Path(path_type=Path), default=None,
              help="Path for DOT file export")
@click.option("--html-out", type=click.Path(path_type=Path), default=None,
              help="Path for interactive HTML export")
@click.option("--no-file-nodes", is_flag=True,
              help="Exclude FILE nodes from visual exports")
@click.option("--no-transitive", is_flag=True,
              help="Remove transitive edges")
@click.option("--index", "index_out", type=click.Path(path_type=Path), default=None,
              help="Path for ARTIFACT_INDEX.md")
@click.option("--index-auto", is_flag=True,
              help="Generate index at default path")
@click.option("-v", "--verbose", is_flag=True, help="Show detailed info")
def main(root: Path, json_out: Optional[Path], dot_out: Optional[Path],
         html_out: Optional[Path],
         no_file_nodes: bool, no_transitive: bool,
         index_out: Optional[Path], index_auto: bool, verbose: bool):
    """Traceability Scanner — parse BA artifacts and verify cross-references."""
    root = root.resolve()
    config = load_config(root)

    registry = scan_definitions(root, config)
    if verbose:
        print(f"[scan] {len(registry)} artifact definitions found")

    references = scan_references(root, registry, config)
    index_xrefs = scan_index_cross_refs(root, config)
    code_refs = scan_code_references(root, config)
    test_refs = scan_test_references(root, config)
    if verbose:
        print(f"[scan] {len(references)} references found, {len(index_xrefs)} index cross-refs, "
              f"{len(code_refs)} code trace refs, {len(test_refs)} test refs")

    G = build_graph(registry, references, config, index_xrefs, code_refs, test_refs)
    report = verify(G, registry, references, config)
    print_report(report, registry, config, verbose)

    if json_out:
        export_json(G, registry, report, json_out)

    G_vis = _filter_graph(G, no_file_nodes, no_transitive, verbose)

    if dot_out:
        export_dot(G_vis, config, dot_out)
    if html_out:
        export_html(G_vis, config, html_out)

    # Index generation
    idx_path = index_out
    if not idx_path and index_auto:
        # Find first scan dir that exists
        for d in config.scan_dirs:
            p = root / d
            if p.exists():
                idx_path = p / "ARTIFACT_INDEX.md"
                break
    if idx_path:
        export_index(G, registry, config, root, idx_path)


if __name__ == "__main__":
    main()
